# Generated by Django 5.1.7 on 2026-06-13 22:09

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Moto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('immatriculation', models.CharField(max_length=30, unique=True)),
                ('marque', models.CharField(max_length=80)),
                ('modele', models.CharField(max_length=80)),
                ('etat', models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('AFFECTEE', 'Affectée'), ('EN_MISSION', 'En mission'), ('HORS_SERVICE', 'Hors service')], default='DISPONIBLE', max_length=20)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['immatriculation'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('RESPONSABLE', 'Responsable'), ('LIVREUR', 'Livreur')], default='RESPONSABLE', max_length=20)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Livreur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=80)),
                ('prenom', models.CharField(max_length=80)),
                ('telephone', models.CharField(max_length=30)),
                ('adresse', models.TextField()),
                ('numero_permis', models.CharField(max_length=60, unique=True)),
                ('numero_cni', models.CharField(max_length=60, unique=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='livreurs/')),
                ('actif', models.BooleanField(default=True)),
                ('utilisateur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profil_livreur', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['nom', 'prenom'],
            },
        ),
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_client', models.CharField(max_length=120)),
                ('telephone_client', models.CharField(max_length=30)),
                ('adresse_livraison', models.TextField()),
                ('description_lieu', models.TextField(blank=True)),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('EN_COURS', 'En cours'), ('TERMINEE', 'Terminée'), ('ANNULEE', 'Annulée')], default='EN_ATTENTE', max_length=20)),
                ('otp', models.CharField(editable=False, max_length=6)),
                ('otp_valide_le', models.DateTimeField(blank=True, null=True)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('modifie_le', models.DateTimeField(auto_now=True)),
                ('livreur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='missions', to='tracking.livreur')),
                ('moto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='missions', to='tracking.moto')),
            ],
            options={
                'ordering': ['-cree_le'],
            },
        ),
        migrations.CreateModel(
            name='PreuveLivraison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.CharField(max_length=120)),
                ('otp_valide', models.CharField(max_length=6)),
                ('valide_le', models.DateTimeField(default=django.utils.timezone.now)),
                ('livreur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='preuves', to='tracking.livreur')),
                ('mission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preuve', to='tracking.mission')),
                ('moto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='preuves', to='tracking.moto')),
            ],
            options={
                'ordering': ['-valide_le'],
            },
        ),
        migrations.CreateModel(
            name='Affectation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_fin', models.DateTimeField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('livreur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='affectations', to='tracking.livreur')),
                ('moto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='affectations', to='tracking.moto')),
            ],
            options={
                'ordering': ['-date_debut'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('active', True)), fields=('moto',), name='unique_moto_affectation_active'), models.UniqueConstraint(condition=models.Q(('active', True)), fields=('livreur',), name='unique_livreur_affectation_active')],
            },
        ),
        migrations.CreateModel(
            name='PositionGPS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('date_appareil', models.DateField(blank=True, null=True)),
                ('heure_appareil', models.TimeField(blank=True, null=True)),
                ('recue_le', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('moto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='tracking.moto')),
            ],
            options={
                'ordering': ['-recue_le'],
                'indexes': [models.Index(fields=['moto', '-recue_le'], name='tracking_po_moto_id_3f54d8_idx')],
            },
        ),
    ]
