# Generated by Django 5.1.7 on 2026-06-14 16:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0002_user_telephone'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='destination_latitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='mission',
            name='destination_longitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('type', models.CharField(choices=[('GPS_DECONNECTE', 'GPS déconnecté'), ('SORTIE_ZONE', 'Sortie de zone'), ('VALIDATION_COMMANDE', 'Validation de commande')], max_length=30)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(db_index=True, default=False)),
                ('mission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alertes', to='tracking.mission')),
                ('moto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alertes', to='tracking.moto')),
            ],
            options={
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['type', 'is_read'], name='tracking_al_type_3e8d7b_idx'), models.Index(fields=['moto', 'type', 'is_read'], name='tracking_al_moto_id_82da28_idx')],
            },
        ),
    ]
