# Generated by Django 5.1.7 on 2026-06-14 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0003_mission_destination_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='type',
            field=models.CharField(choices=[('GPS_DECONNECTE', 'GPS déconnecté'), ('SORTIE_ZONE', 'Sortie de zone'), ('VALIDATION_COMMANDE', 'Validation de commande'), ('MISSION_ASSIGNEE', 'Mission assignée'), ('MISSION_ANNULEE', 'Mission annulée')], max_length=30),
        ),
    ]
