# Generated by Django 5.1.7 on 2026-06-15 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0004_alter_alert_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='livreur',
            name='date_debut_contrat',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='livreur',
            name='date_fin_contrat',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='livreur',
            name='document_contrat',
            field=models.FileField(blank=True, null=True, upload_to='contrats/'),
        ),
        migrations.AddField(
            model_name='livreur',
            name='type_contrat',
            field=models.CharField(choices=[('CDD', 'CDD'), ('CDI', 'CDI')], default='CDI', max_length=3),
        ),
    ]
