# Generated by Django 5.1.7 on 2026-06-15 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0005_livreur_date_debut_contrat_livreur_date_fin_contrat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='is_archived',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
